services:
  mc2.crudtest.api:
    image: mc2.crudtest.api
    build:
      context: .
      dockerfile: Mc2.CrudTest.Api/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CustomerTest;User=sa;Password=Mofid777;Integrated Security=False ;TrustServerCertificate=True;

    networks:
      - app-network
   

  sqlserver:
        image: mcr.microsoft.com/mssql/server
        environment:
          SA_PASSWORD: Mofid777
          ACCEPT_EULA: "Y"
          MSSQL_PID: Express
          MSSQL_USER: sa
          MSSQL_PASSWORD: Mofid777
        ports:
          - "1433:1433"
        networks:
          - app-network

networks:
  app-network:
   driver: bridge